yearn/yearn-vaults

.github/workflows/lint.yaml, .github/workflows/test.yaml
Configure CI to only run `master` and `develop` branches and PRs
=> feat: fix github ci/cd

contracts/BaseStrategy.sol, contracts/Vault.vy, ethpm-config.yaml, tests/functional/vault/test_config.py
- Updated default symbol to `concat("yv", DetailedERC20(_token).symbol())`
- Updated default name to `self.name = concat(DetailedERC20(_token).symbol(), " yVault")`
- Adds setName and setSymbol methods for governance
- Updated Vault deployment tests
- Added new tests for setName and setSymbol
=>  Add setName and setSymbols governance methods

contracts/Vault.vy, tests/functional/vault/test_shares.py
Fixes #27 and replaces #36 
This effectively allows a deposit/withdrawal + transfer in one call. In the case of withdrawals, the recipient receives the tokens and in the case of deposits, the recipient receives the vault shares.
- Moves withdraw logic from external method to internal `_withdrawFrom`
- Adds external `withdrawAll` method
- Adds `_recipient` support to internals `_depositFrom` and `_withdrawFrom`
- Defaults `_recipient` to `msg.sender` in external methods (`deposit`, `depositAll`, `withdraw`, `withdrawAll`)
- Updates withdraw* methods to return number of tokens withdrawn
- Adds test for `withdrawAll`
- Adds tests for cases where the recipient is specified
WIP until there's confirmation that the default arg approach is the right one instead of additional methods requiring …
=> feat: Add recipient support to withdraw* and deposit* methods

contracts/BaseStrategy.sol, contracts/Vault.vy, contracts/test/TestStrategy.sol, tests/functional/strategy/test_config.py, tests/functional/vault/test_config.py
=> Updates to Strategy API

contracts/Vault.vy, tests/functional/vault/test_shares.py
Removes the overly onerous approval check as a mitigation for a minor vulnerability in ERC20 implementation.
=> refactor: remove additional check on approvals

contracts/Vault.vy, tests/functional/vault/test_shares.py
Since we removed the mitigation on approvals in #44, it makes sense to add the recommended mitigation which is 2 functions that atomically change the allowance
=> Add increase/decrease allowance functions

contracts/BaseStrategy.sol, contracts/Vault.vy, contracts/test/TestStrategy.sol, ethpm-config.yaml, tests/functional/strategy/test_config.py, tests/functional/strategy/test_misc.py, tests/functional/strategy/test_shutdown.py, tests/functional/strategy/test_startup.py, tests/functional/vault/test_config.py, tests/functional/vault/test_misc.py
A series of fixes to simplify how strategist use `BaseStrategy`
Bumped API Version to 0.1.3
=> Refactor Strategy API

contracts/Vault.vy
Applies some of the updates from #52 to reduce conflicts
=> Vyper Linting Updates

SPECIFICATION.md
Possible typo. A Strategy borrows from the Vault, not another Strategy.
=> fix: change Strategy to Vault

contracts/Vault.vy, tests/functional/strategy/test_rate_limit.py
Have `rateLimit = 0` explicitly shut off the rate limiter, instead of letting a large number implicitly disable it.
We were seeing test case issues because of the implicit check, as brownie tests execute too quickly for the implicit disable to work properly. An explicit disable is better, and avoids potential div / 0 faults from an improperly configured rate limit.
The new behavior is that 0 is disabled, and >0 is not
TODO:
=> Change Rate Limit disable

contracts/Vault.vy, tests/functional/vault/test_config.py
When the vault has no funds, `pricePerShare` reverts with a zero division.
That's because the external method calls `_shareValue` which does a division by `totalSuppy`.
=> fix: div by zero

contracts/Vault.vy
This could be used to make a universal GuestList which rate limits starting from the Vault deployment.
=> Store Vault activation timestamp

contracts/Vault.vy, tests/functional/vault/test_permit.py
Implement `permit` approval by signature.
Inspired by [EIP-2612](https://eips.ethereum.org/EIPS/eip-2612) draft, but doesn't follow it verbatim.
Notable deviations:
- EIP-712 domain `name` is fixed as `Yearn Vault` since contract name is mutable.
- EIP-712 domain `version` is read from `apiVersion`.
- `Permit` message uses `amount` instead of `value` as argument name because `value` is reserved in Vyper.
- Signature is encoded as `Bytes[65]` of packed `r, s, v` instead of three args.
- The function returns True, this part is arguable, since it's is unclear from the spec.
References:
- [Uniswap](https://github.com/Uniswap/uniswap-v2-core/blob/4dd59067c76dea4a0e8e4bfdda41877a6b16dedc/contracts/UniswapV2ERC20.sol#L81)
- [DAI](https://github.com/makerdao/dss/blob/36dab5c9fdce4fc36812e4fd8228be …
=> feat: add permit

contracts/Vault.vy, tests/functional/vault/test_permit.py
Change permit type hash to the one defined by [EIP-2612](https://eips.ethereum.org/EIPS/eip-2612).
This will allow to use off-the-shelf examples for Permit messages:
```
{
"types": {
"EIP712Domain": [
{"name": "name", "type": "string"},
{"name": "version", "type": "string"},
{"name": "chainId", "type": "uint256"},
{"name": "verifyingContract", "type": "address"},
],
"Permit": [
{"name": "owner", "type": "address"},
{"name": "spender", "type": "address"},
{"name": "value", "type": "uint256"},
{"name": "nonce", "type": "uint256"},
{"name": "deadline", "type": "uint256"},
],
},
"domain": {
"name": "Yearn Vault",
"version": vault.apiVersion(),
"chainId": 1,
"verifyingContract": str(vault),
},
"primaryType": "Permit",
"message": {
"owner": owner,
"spender": spender,
"value": value,
"nonce": …
```
=> feat: standard permit

contracts/Vault.vy, tests/functional/vault/test_strategies.py
Change Log:
* adds assertions for checking want and vault address when adding a strategy
* updates unit test
=> fix: check for strategy vault and want address matches on add

contracts/Vault.vy
fixes: #117
only allow governance to undo a Vault shutdown
originally #118
=> fix: set correct access control for setEmergencyShutdown

SPECIFICATION.md, contracts/Registry.vy, contracts/Vault.vy, scripts/deploy.py, tests/conftest.py, tests/functional/conftest.py, tests/functional/registry/conftest.py, tests/functional/registry/test_config.py, tests/functional/registry/test_deployment.py, tests/functional/registry/test_release.py, tests/functional/strategy/test_migration.py, tests/functional/vault/test_config.py, tests/functional/vault/test_losses.py, tests/functional/vault/test_misc.py, tests/functional/vault/test_shares.py, tests/functional/vault/test_strategies.py, tests/functional/vault/test_withdrawal.py, tests/integration/conftest.py, tests/integration/test_release.py
fixes: #45 
fixes: #47 
This PR takes the concept of the "Vault Registry" and simplifies it down to the bare bones: managing an ordered list of Vault releases and deployments. From these lists, it will be possible to further specialize around this, towards the final goal of making it possible to get a snapshot of the entire Yearn Vault ecosystem from one contract address.
There are two specializations for Vaults:
1. "Experimental" or community-deployed Vaults (unendorsed by Yearn)
2. "Endorsed" vaults, explicitly managed by Yearn, and considered a part of the Yearn ecosystem
TODO:
=> feat: simplified vault registry

contracts/BaseStrategy.sol, contracts/Vault.vy, contracts/test/TestStrategy.sol
fixes: #40 
fixes: #82
This PR consolidates the two similar functions `exitPosition` and `liquidatePosition` together, by adding another value that `liquidatePosition` returns (e.g. "realized loss"). The realized loss is reported during `Vault.report` (with `Strategy.emergencyShutdown` active) or `Vault.withdraw` and assessed to maintain the integrity of the Vault's balance sheet during those events. Further, the realized loss during withdrawals is fully applied to the withdrawer instead of socialized to the Vault, which should help prevent any "slippage" attacks against strategies connected to the Vault from being exploitable in practice.
=> refactor: consolidate `exitPosition` into `liquidatePosition`

contracts/Vault.vy, tests/functional/conftest.py, tests/functional/registry/conftest.py, tests/functional/strategy/test_migration.py, tests/functional/vault/test_config.py, tests/functional/vault/test_losses.py, tests/functional/vault/test_shares.py, tests/functional/vault/test_strategies.py, tests/functional/vault/test_withdrawal.py, tests/integration/conftest.py
fixes #121 
- Remove set deposit limit to `2 ** 256 - 1` in `initialize`
- By default, deposit limit is `0` on construction (must call `setDepositLimit` afterwards to enable deposits)
- Removes `UpdateDepositLimit` event in `initialize`
- Updates all necessary tests & documentation
=> feat: vault deposit limit zero on initialization

contracts/BaseStrategy.sol, contracts/Vault.vy, tests/functional/conftest.py, tests/functional/strategy/test_fees.py, tests/functional/strategy/test_misc.py, tests/functional/strategy/test_rate_limit.py, tests/functional/strategy/test_shutdown.py, tests/functional/strategy/test_startup.py, tests/functional/strategy/test_withdrawal.py, tests/functional/vault/test_config.py, tests/functional/vault/test_losses.py, tests/functional/vault/test_misc.py, tests/functional/vault/test_strategies.py, tests/functional/vault/test_withdrawal.py, tests/integration/test_operation.py
fixes: #139
This PR transitions the Strategy debt limit from an absolute value to a ratio of the total assets of the Vault. This change introduces some dynamic behavior to the Vault, as this value is based on user deposits. This has the additional benefit of scaling up as the Vault's deposits fluctuate so governance/management does not have to manage these values as often.
This introduction should be safe as the use of `Vault.totalAssets()` to determine the absolute amount at the time of `Vault.report()` (from `Strategy.harvest()`) has the same safety conditions as `Vault.deposit()`/`Vault.withdraw()`. Additionally, `Strategy.harvestTrigger()` takes into account `Vault.creditAvailable(strategy)`, so integrations may need to watch for additional behavioral changes as this may make it more …
=> feat: use debt ratio vs. absolute debt limit

contracts/BaseStrategy.sol, contracts/Vault.vy, contracts/test/TestStrategy.sol, tests/functional/strategy/test_config.py, tests/functional/strategy/test_fees.py, tests/functional/strategy/test_migration.py, tests/functional/strategy/test_misc.py, tests/functional/vault/test_strategies.py, tests/functional/vault/test_withdrawal.py
Change Log:
* adds check for shutdown flag in addStrat method. Audit Issue 5.1
* fix definition of reportDelay value setter and comments . Audit Issue 5.4
* sanity check for max fees. Audit Issue 5.6
* sanity check for adding 0x0 strat. Audit Issue 5.7
* fix sync rate limit comments. Audit Issue 5.18
* removes unused method in vault Api interface. Audit Issue 5.21
* add sanity checks to params. Audit Issue 5.22
* enforce loss report value with check. Audit Issue 5.24
* adds reentrancy guard and test to withdraw. Audit Issue 5.26
* removed superfluos min check. Audit Issue 5.36
* add event for emergency exit activation in strategy. Audit Open Q 6.2
* corrected comment on setRewards in `BaseStrategy`. Audit Open Q 6.5
=> fix: various issues for release

contracts/Vault.vy, contracts/test/TestStrategy.sol, tests/functional/vault/test_withdrawal.py
requires: #141
This small change allows the user to specify the maximum amount of losses they are willing to sustain during a withdrawal (see #140). The default is 0%, so any realized loss will cause an abort
=> feat: protect against excessive losses

scripts/deploy.py
The `newExperimentalVault(...)` function in the [current registry contract](https://etherscan.io/address/0xe15461b18ee31b7379019dc523231c57d1cbc18c#writeContract) expects `guardian` at argument index 2 instead of 3.
Also when deploying experimental vaults, default `governance` to the `dev` address to make it easier to set it up.
=> Deploy script improvements

tests/functional/vault/test_strategies.py
@fubuloubu  Would that do for: `Vault.report()` w/ 0% fees & profit ?
=> test: add reporting gains tests

tests/functional/vault/test_withdrawal.py
Issue #176 
Created PR for discussion @fubuloubu. At first glance it seems reentrancy guard is not working as expected,
can check out branch and run the test `test_withdrawal_with_reentrancy`. 
Issue:
Withdraw transaction in `test_withdrawal_with_reentrancy` is not failing as expected.
Expectation: 
Withdraw transaction should fail, when we setup strategy for reentrancy back to vault.
=>  fix: reentrancy guard test not failing correctly

contracts/BaseStrategy.sol, tests/functional/strategy/test_fees.py
This change sets approval to allow strategists to withdraw vault LP tokens from the vault using transferFrom rather than having them distributed on every harvest. 
This saves gas by not distributing every harvest. 
It also solves a problem with the [strategist sharer contract](https://github.com/Grandthrax/Sharer/blob/master/contracts/SharerV2.sol). We cannot tell which contract sent the rewards and so cannot differentiate between rewards from different strategies on the same vault.
=> feat: pull strategist rewards rather than push

tests/functional/registry/test_config.py, tests/functional/registry/test_deployment.py, tests/functional/registry/test_release.py
Increases Registry test coverage to 100%. In particular, there was some missing
branch coverage in the following:
* Registry.newRelease()
* Registry.newVault()
* Registry.endorseVault()
The missing branch coverage was all on asserts, so this change just creates
some negative tests to check for reverts.
Partial work towards #156.
=> test: increase Registry test coverage

contracts/test/TestStrategy.sol, tests/functional/strategy/test_misc.py
Currently, `TestStrategy` does not have any protected tokens. In order to get full test coverage of `BaseStrategy.sweep()`, this change adds a (fake) protected token address to `TestStrategy` and tests sweep on that address, checking for a revert.
It also tests that sweep reverts if given the vault shares address.
Partial progress towards #156.
=> test: increase coverage for BaseStrategy.sweep()

tests/functional/strategy/test_config.py, tests/functional/strategy/test_misc.py, tests/functional/strategy/test_shutdown.py
This includes a handful of coverage improvements for BaseStrategy. After the change, the only issues shown by `brownie gui` are in the `only*` modifiers.
The overall coverage goes from 80.6% -> 86%, but I think that includes all of TestStrategy and its dependencies, which dilutes the coverage numbers a bit. Just focusing on BaseStrategy, I think coverage will be in pretty good shape with this PR.
Current coverage:
```
contract: TestStrategy - 80.6%
Address.functionCall - 100.0%
Address.isContract - 100.0%
BaseStrategy.apiVersion - 100.0%
BaseStrategy.governance - 100.0%
BaseStrategy.isActive - 100.0%
BaseStrategy.migrate - 100.0%
BaseStrategy.setDebtThreshold - 100.0%
BaseStrategy.setMaxReportDelay - 100.0%
BaseStrategy.setMetadataURI - 100.0%
BaseStrategy.setMinReportDelay - 100.0% …
```
=> test: increase coverage of BaseStrategy

contracts/BaseStrategy.sol, contracts/test/TestStrategy.sol, contracts/utils/ProxyFactoryInitializable.sol, tests/functional/conftest.py, tests/functional/strategy/test_config.py
Reduce deployment costs if you have template strategies. Instead of inherit, delegate storage for params to minimal proxies.
e.g. https://github.com/emilianobonassi/yIdleStrategies/blob/dev/contracts/StrategyIdle.sol
=> feat: proxy mode support for BaseStrategy via BaseStrategyInitializable

contracts/Vault.vy
According to the Gregorian Calendar, leap years usually occur every 4th year but are skipped every 100 years unless the year is divisible by 400. 400, 800, 1200, 1600, and 2000 ARE leap years but 100, 200,300, 500 . are not.  Thus 2000 is a leap year but 1900 and 2100 are not.  A four-century period will be missing 3 of its 100 Julian leap years, leaving 97.  So the **average year** has 365 + 97/400 = **365.2425** days.
1 year (365 days) | 31536000 seconds
-- | --
1 year (avg. 365.24 days) | 31556926 seconds
leap year (366 days) | 31622400 seconds
| ****                                               | **AverageYear(Days)** | **ErrorPerYear(Days)** | **ErrorRatio** | **CylcePeriod** | **1-DayShift** | **100-yearError(Days)** |
|----------------------------------------------------|---------- …
=> fix(time): fixes SECS_PER_YEAR to gregorian constant

contracts/Registry.vy, tests/functional/registry/test_deployment.py, tests/functional/wrappers/test_affliate.py, tests/functional/wrappers/test_ytoken.py, tests/integration/test_wrapper.py
=> fix: explicitly add Vaults to Registry

contracts/Registry.vy, contracts/Vault.vy, tests/functional/vault/test_misc.py
fixes: #189
Note: the v0.2.11 release contains an internal upgrade to Vyper such that EIP-1167 forwarder-style proxies are now the default for `create_forwarder_to`, among some other minor improvements to gas costs and bytecode size.
=> chore: upgrade to vyper v0.2.11

contracts/BaseWrapper.sol
Failure found in https://github.com/yearn/yearn-vaults/runs/2060926601
=> fix: allow for some small loss on migration, but disallow underflows

contracts/BaseStrategy.sol, tests/functional/strategy/test_clone.py
=> fix: Add state variables default initialisation to _initializate()

contracts/Registry.vy, tests/functional/registry/test_deployment.py
Added the ability to track endorsed vault tokens in the registry.
- Only support adding tokens if they've not yet been added
- Only keep track of tokens for endorsed vaults (deployments)
=> feat(registry): add ability to track endorsed vault tokens

contracts/BaseWrapper.sol, contracts/Registry.vy, tests/functional/registry/test_config.py, tests/functional/wrappers/test_affliate.py, tests/functional/wrappers/test_ytoken.py, tests/integration/test_release.py
This would have driven me crazy if we didn't standardize this before redeploying
=> refactor: standardize terminology for vaults in registry

contracts/BaseStrategy.sol, contracts/Vault.vy, contracts/test/TestStrategy.sol, tests/functional/strategy/test_fees.py
This PR changes how fees are assessed such that `BaseStrategy.delegatedAssets` is pro-rated into the fee assessment. If a strategy delegates all of it's assets, there should be no fees earned by that strategy to either governance or the strategist themselves, and that portion of the assets loaned out shall earn no management fees either.
If only a portion is delegated (e.g. debt-based strategies where some of the funds are used to borrow against), that portion should be calculated such that the exact funds used to borrow are marked as delegated (e.g. Maker strategy w/ 200% debt ratio, then half the funds should be marked "delegated"). This is important to ensure than the degree of work is properly accounted for in how a strategy operates.
Strategists will need to be aware of properly …
=> refactor: delegated fees

docs/OPERATIONS.md, scripts/deploy.py
Change Log:
-update ops checklist with new registry instructions for vault with prev release versions
-update deploy script to have option for different releases
=> feat: update ops manual on endorsing previous release vaults

docs/OPERATIONS.md
This notice was meant to prevent the creation of new releases with experimental vaults. That has changed and vaults are not automatically endorsed when creating a new release using the registry.
=> fix: remove old warning

contracts/BaseWrapper.sol, contracts/test/AffiliateToken.sol, tests/functional/wrappers/test_affliate.py
First bug:
See:
1.https://github.com/yearn/brownie-wrapper-mix/blob/master/contracts/AffiliateToken.sol#L101
Here share is calculated before the deposit.
2. If we consider the situation in which MAX UINT256 passed as input
https://github.com/yearn/brownie-wrapper-mix/blob/master/contracts/AffiliateToken.sol#L98
3. When we pass the MAX_UINT value, the vulnerability appears in this code.
See:
1.https://github.com/yearn/brownie-wrapper-mix/blob/master/contracts/AffiliateToken.sol#L101
Here share is calculated before the deposit.
2. If we consider the situation in which MAX UINT256 passed as input
https://github.com/yearn/brownie-wrapper-mix/blob/master/contracts/AffiliateToken.sol#L98
3. When we pass the MAX_UINT value, the vulnerability appears in this code.
Since share will be calculated …
=> Fix: deposit everything to AffiliateToken

docs/OPERATIONS.md
Fixed the addStrategy command in the doc. Included a reference table for Yearn addresses.
=> docs: updated addStrategy for latest vault version

README.md, brownie-config.yaml, contracts/BaseStrategy.sol, contracts/BaseWrapper.sol, contracts/test/AffiliateToken.sol, contracts/test/TestGuestList.sol, contracts/test/TestStrategy.sol, contracts/test/Token.sol, contracts/yToken.sol, yarn.lock
Waiting on openzeppelin 4 final release.
fixes #153
=> Update to solidity 0.8

contracts/test/AffiliateToken.sol
I believe the withdrawal functionality in AffiliateToken.sol is incorrect due to the ordering of operations within the function. The shares are burned before the _shareValue() call within the function (which returns the number of underlying tokens the burned shares can be redeemed for). This results in the totalSupply() being different than expected within this calculation.
As an example scenario:
- An ERC20 token (mockToken) was deployed
- Yearn Token Vault V 0.2.11 was deployed and initialized with the ERC20 token's address.
- The vault's deposit limit was set to 24 (mockToken)
- Yearn's Registry V 0.2.11 was deployed
- The vault was added as a newRelease to the registry and it was endorsed with endorseVault.
- The AffiliateToken wrapper was deployed with the mockToken's address and the …
=> fix: affiliate token withdraw calculation

tests/conftest.py, tests/functional/strategy/test_misc.py
We had a fix for mismatching `chain.id` and `chainid()` (1337 vs 1) in ganache, but hardhat doesn't have this problem (both are 31337). This change only applies the fix for ganache. This only affects `permit` tests.
=> test: hardhat compatibility

.github/workflows/title.yaml
This makes sure when we use the "squash and merge" feature, the default option for the squash commit message (e.g. the PR title) is compliant with conventional commits
=> chore: check PR titles for conventional commits

contracts/Vault.vy, tests/functional/vault/test_config.py
=> fix: prevent setting wrong reward address

contracts/Vault.vy
=> fix: check erc20 decimals

contracts/Vault.vy, tests/functional/vault/test_shares.py
=> fix: prevent shares from being deposited to wrong address

contracts/BaseStrategy.sol, tests/functional/strategy/test_shutdown.py
=> feat: setEmergencyExit should allow to be called by vault guardian and vault management

contracts/Vault.vy
Fix comments in `Vault.vy`
1. The default symbol starts with `yv` instead of `y`
2. Gas of 2 SLOADs drops from 4000 to 200.
=> fix: comments in Vault.vy 

contracts/Vault.vy
As @zgfzgf pointed out on #333 the precision factor isn't improving precision most of the time.
It would only be useful if we were doing a multiplication after a division.
=> fix: precision factor is useless

contracts/Vault.vy, tests/functional/vault/test_losses.py
=> fix: prevent division per zero

contracts/BaseStrategy.sol, contracts/test/TestStrategy.sol
=> fix: inconsistent Liquidations in BaseStrategy Emergency Exit Mode

contracts/Vault.vy, tests/functional/strategy/test_fees.py
=> fix: performanceFee error

contracts/Vault.vy
https://github.com/yearn/yearn-vaults/blob/master/contracts/Vault.vy#L1044
https://github.com/yearn/yearn-vaults/blob/master/contracts/Vault.vy#L1089-L1090
this condition does not change unless tokens are withdrawn from strategies, so move the code  to where it can possibly be true.
=> refactor: move condition shares calculation and save gas

contracts/Vault.vy, tests/functional/strategy/test_fees.py
assert performanceFee <= MAX_BPS - self.performanceFee 
change to
assert performanceFee <= MAX_BPS / 2
=> fix: strategy performance fee

contracts/Vault.vy, tests/functional/vault/test_losses.py, tests/functional/vault/test_withdrawal.py
1 - Make sure that we deposit and withdraw at same share price
2 - Add onreleased profit to next lockedprofit
=> feat: locked profit on deposit

contracts/Vault.vy
It's almost the same as #345 
@fubuloubu  in #345 you said:"This method also assesses the management fee, which is being skipped by this update"
as in #363 add var managementDebt
If there is no need to retain management fee, the PR is OK.
=> perf: assessFees when gain==0

tests/functional/vault/test_misc.py, tests/functional/vault/test_strategies.py, tests/functional/vault/test_withdrawal.py
Don't use List generator for looping or side-effect.
It will unnecessarily waste memory.
=> fix: removed anti-patterns from tests

scripts/deploy.py
order was wrong
```
token: address,
governance: address,
rewards: address,
nameOverride: String[64],
symbolOverride: String[32],
guardian: address = msg.sender,
management: address =  msg.sender,
```
=> fix: deployement parameters

contracts/BaseStrategy.sol, tests/functional/strategy/test_config.py, tests/functional/strategy/test_misc.py, tests/functional/strategy/test_shutdown.py
=> refactor: reduce base strategy size

contracts/Vault.vy
=> fix: shares for amount calculation should use freeFunds

contracts/BaseWrapper.sol
When depositing everything, the safeApprove is triggered every time, this will reduce the gas usage.
=> fix: save gas on DEPOSIT_EVERYTHING not re approving

contracts/Vault.vy, requirements-dev.txt
Upgrading the vault version to the latest version of vyper (0.3.0)
=> chore: bump vyper version

contracts/Vault.vy, tests/functional/vault/test_losses.py
Here's an edge case of small loss not dropping the debt ratio.
The "root issue" is:
```
ratio_change: uint256 = min(
loss * self.debtRatio / self.totalDebt,
self.strategies[strategy].debtRatio,
)
```
min there works like `min(int(a), int(b))`. if loss is small enough, `loss * self.debtRatio / self.totalDebt` will be greater than 0 but smaller than 1.
=> feat: test small losses

contracts/BaseStrategy.sol
It moves the `require(isOriginal)` statement to the main `clone` function due to any strategist might call it without verifying whether it is the original strategy or not.
Fixes # (issue) NA
=> fix: move require isOriginal to main clone function

contracts/BaseRouter.sol
Changes one letter in BaseRouter.sol / description of bestVault() view function.
Same description at BaseWrapper.sol#L38.
typo
=> docs: changes letter v in revent to c

contracts/Vault.vy, contracts/test/SimpleStrategy.sol, tests/functional/conftest.py, tests/functional/vault/test_shares.py
When withdrawing using a vault's withdraw method the vault will withdraw from strategies in the withdrawal queue if the vault's token balance doesn't directly cover the calculated withdrawal value. Furthermore if depleting the strategies still doesn't cover the necessary withdrawal amount after deducting strategy losses the vault will recalculate the share amount to be burnt.
Fixes # (bug reported in immunefi)
=> fix: assert shares amount before withdrawing

tests/functional/conftest.py, tests/functional/vault/test_shares.py, tests/functional/vault/test_withdrawal.py
Fix the way, the number of shares are calculated from token balance. 
In various places at [test_withdrawal.py](https://github.com/yearn/yearn-vaults/blob/main/tests/functional/vault/test_withdrawal.py#L179), the token balance is converted to vault shares via: `token_balance * vault.pricePerShare() // 10 ** vault.decimals()`.
This seems incorrect as we're multiplying `token_balance` with number of tokens each share represents.
The correct calculation should be: `token_balance // vault.pricePerShare() * (10 ** vault.decimals())`.
The test still passes because in all these cases `vault.pricePerShare() // 10 ** vault.decimals()` turns out to be `1`.
Fixes https://github.com/yearn/yearn-vaults/issues/515
=> fix: update token balance to share calculation

.github/workflows/test.yaml
Fixed a small typo in the test CI
=> fix: test CI typo

.gitattributes
because github renders by default
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> chore: .gitattributes file no longer needed

.gitignore, contracts/BaseStrategy.sol, contracts/Vault.vy, ethpm-config.yaml
Increase characters allowed for `setSymbol()` and `setName()`, needed for factory vaults
=> feat: 0.4.6 release
