SPECIFICATION.md
=> docs: fix specification typos

SPECIFICATION.md
Updates to the docs for some changes in recent versions
=> docs: adjusted specification to match current design

contracts/BaseStrategy.sol, tests/functional/strategy/test_config.py
=> Update debt-based harvest trigger with simpler parameter

README.md, contracts/BaseStrategy.sol, contracts/Vault.vy, scripts/deploy.py
=> fix: rename yEarn to Yearn as per Style Guide

contracts/Vault.vy, tests/functional/vault/test_misc.py
This allows recovering less than full balance of ERC20 and also adds an ability to recover ERC721.
=> Add sweep amount

contracts/Vault.vy, tests/functional/vault/test_shares.py
=> Use remaining deposit limit when depositing all

contracts/Vault.vy, tests/functional/conftest.py, tests/functional/vault/test_strategies.py, tests/functional/vault/test_withdrawal.py, tests/integration/test_operation.py
Change the defaults according to the proposed fee schedule.
- Vault performanceFee 4.5% => 10%
- Strategy performanceFee 0.5% => 10%
=> Update default fee settings

contracts/BaseStrategy.sol, contracts/Vault.vy, contracts/test/TestStrategy.sol, tests/functional/vault/test_losses.py, tests/functional/vault/test_misc.py, tests/functional/vault/test_strategies.py
=> Add ability to report losses

tests/functional/strategy/test_migration.py, tests/functional/strategy/test_shutdown.py, tests/functional/strategy/test_startup.py, tests/functional/vault/test_strategies.py
Based on: #74
Why didn't I know this feature existed?
=> Refactor all tests to use dict returns for structs

contracts/Vault.vy, tests/functional/strategy/test_startup.py, tests/functional/vault/test_misc.py
=> feat: add Available Deposit Limit as view-only function

contracts/Vault.vy, contracts/test/TestGuestList.sol, tests/functional/vault/test_shares.py
fixes: #71 
Co-authored-by: banteg <banteeg@gmail.com>
Co-authored-by: Just somie guy <3859395+fubuloubu@users.noreply.github.com>
=> feat: add guest list (#71)

contracts/BaseStrategy.sol, contracts/Vault.vy, tests/functional/conftest.py, tests/functional/strategy/test_misc.py, tests/functional/strategy/test_shutdown.py, tests/functional/strategy/test_startup.py, tests/functional/strategy/test_withdrawal.py, tests/functional/vault/test_losses.py, tests/functional/vault/test_strategies.py, tests/functional/vault/test_withdrawal.py, tests/integration/test_operation.py
=> Move from block-based calculations to timestamps

contracts/BaseStrategy.sol, contracts/Vault.vy, contracts/test/TestStrategy.sol, ethpm-config.yaml, tests/functional/strategy/test_shutdown.py, tests/functional/vault/test_misc.py, tests/functional/vault/test_strategies.py
=> Add Debt Payments to Vault.report

contracts/Vault.vy
NOTE: Should not deploy the Vault with a deflationary token
=> Remove some unused configuration notes/code

contracts/BaseStrategy.sol, contracts/test/TestStrategy.sol
=> feat: improve exitPosition logic

tests/functional/strategy/test_misc.py, tests/functional/vault/test_shares.py
Because it's annoying and I hate it
=> Fix weird intermittent test failure in CI

contracts/BaseStrategy.sol, tests/functional/strategy/test_misc.py
Change Log:
* fixes for issue #105
=> Issue 105: fixes audit report comments for BaseStrategy.sol

contracts/BaseStrategy.sol, contracts/Vault.vy
=> Audit Findings for Vault

requirements-dev.txt, scripts/keep.py
~~depends: https://github.com/eth-brownie/brownie/pull/847~~
=> Upgrade Keeper Script

contracts/BaseStrategy.sol
=> feat: add TVL calculation api

contracts/Vault.vy
Also refactors the input variables a lot to remove the rampent use of `_*` for input args, which was weird
=> chore: upgrade to Vyper 0.2.8

contracts/Vault.vy
fixes: #128 
Adds granular events for the following changes to a vaults parameters/configurations:
- ERC20 name set/updated
- ERC20 symbol set/updated
- Guest list set/updated
- Rewards address set/updated
- Deposit limit set/updated
- Performance fee set/updated
- Management fee set/updated
- Guardian address set/updated
- Emergency shutdown state set (not logged in initialization)
- Withdrawal queue set/updated
Are tests necessary for something this simple? Any feedback/requests on naming or indexed parameters or anything like that? First time using vyper as so appreciate any possible improvements.
Also -- to confirm, no linter for vyper? Followed pattern of two newlines after event declarations.
h/t @fubuloubu
=> feat: add event logs for vault config updates

scripts/deploy.py
This is the script I used to deploy the yHegic vault.
I used @banteg trick for account fetching.
=> feat: better deploy script

contracts/Vault.vy, tests/functional/strategy/test_migration.py, tests/functional/vault/test_strategies.py
=> feat: migrateStrategy shouldn't reset activation time

contracts/BaseStrategy.sol, contracts/test/TestStrategy.sol, tests/functional/strategy/test_config.py, tests/integration/__init__.py
=> feat: remove pure from BaseStrategy name() method

contracts/Vault.vy
=> fix: only charge mgmt fee on invested funds

contracts/test/Token.sol, tests/functional/vault/test_misc.py, tests/functional/vault/test_withdrawal.py
@fubuloubu does that look like what you need help on regarding increasing test coverage on #158 ?
=> test: increase transfer test coverage

contracts/BaseStrategy.sol, contracts/test/TestStrategy.sol, tests/functional/strategy/test_misc.py
closes #165 
I have added the metadataURI to the constructor, I am not sure if that is a requirement ?
=> feat: add metada to base strategy

scripts/deploy.py
Just a quick fix to the deployment script
=> fix: deploy script uses list

contracts/BaseStrategy.sol, contracts/Vault.vy, contracts/test/Token.sol, tests/functional/conftest.py
=> refactor: handle non-compliant ERC20's

contracts/Vault.vy, tests/functional/vault/test_misc.py
=> fix: vault debtRatio update on _reportLoss

contracts/BaseStrategy.sol, contracts/test/Token.sol, tests/functional/conftest.py
=> Fix BaseStrategy constructor not using safeApprove for not compliant ERC20

contracts/BaseStrategy.sol, tests/functional/strategy/test_config.py
=> feat: management and Guardian should be able to harvest() a Strategy

contracts/BaseStrategy.sol, contracts/Vault.vy, ethpm-config.yaml
Bump versions for Release and then create release Bonny for v0.3.2
=> feat: bump release version for Bonny

.prettierrc.json, CONTRIBUTING.md, README.md, SECURITY.md, docs/OPERATIONS.md
Add ops tasks procedure for:
- Deployment of an experimental vault
- Scale-up until production-ready
=> docs: add ops tasks procedure

contracts/test/Token.sol, tests/functional/conftest.py, tests/functional/registry/conftest.py, tests/functional/registry/test_deployment.py, tests/functional/strategy/test_fees.py, tests/functional/strategy/test_migration.py, tests/functional/strategy/test_misc.py, tests/functional/vault/test_misc.py, tests/functional/vault/test_strategies.py, tests/functional/vault/test_withdrawal.py, tests/integration/conftest.py
=> Test multiple decimals

contracts/Registry.vy, tests/functional/registry/test_config.py
fixes #209
@fubuloubu could you have a look at this one?
=> feat: make pendingGovernance public

contracts/Vault.vy
=> feat: increase precision for important calculations

scripts/deploy.py
Update script for latest release
=> chore: update deploy script to new release

docs/DEPLOYMENT.md
=> fix: update code snippet

contracts/Vault.vy, tests/functional/vault/test_shares.py
=> fix: do not issue zero shares

contracts/BaseStrategy.sol, contracts/test/AffiliateToken.sol, tests/functional/strategy/test_clone.py
=> fix: prevent clone of clone

contracts/yToken.sol, tests/functional/wrappers/test_ytoken.py
fixes #319
Dependency: https://github.com/yearn/yearn-vaults/pull/325
=> fix: get ytoken name, symbol and decimal from token

contracts/Vault.vy, tests/functional/strategy/test_config.py, tests/functional/strategy/test_fees.py, tests/functional/strategy/test_migration.py, tests/functional/strategy/test_misc.py, tests/functional/strategy/test_shutdown.py, tests/functional/strategy/test_startup.py, tests/functional/strategy/test_withdrawal.py, tests/functional/vault/test_losses.py, tests/functional/vault/test_misc.py, tests/functional/vault/test_strategies.py, tests/functional/vault/test_withdrawal.py, tests/integration/test_operation.py
=> fix: make sure _assessFees isn't called twice within the same block

contracts/Vault.vy
=> docs: token should not be inflationary, deflationary or transfer fees

contracts/Vault.vy, tests/functional/strategy/test_fees.py
closes https://github.com/yearn/yearn-vaults/issues/321
=> fix: prevent fees to be above 100%

contracts/BaseWrapper.sol
fixes #305
Doing 10 integration tests on: https://github.com/yearn/yearn-vaults/pull/313
=> fix: baseWrapper do not deposit dust 

contracts/Vault.vy
#343 
optimize code
and corresponding to _creditAvailable https://github.com/yearn/yearn-vaults/blob/f7a6bf53e133c9a39d867771c1a7d442b6488710/contracts/Vault.vy#L1471-L1474
It's easier to understand
=> perf: optimize code in func _debtOutstanding

contracts/Vault.vy
=> perf: delete useless management_fee

contracts/BaseWrapper.sol, contracts/Vault.vy
@fubuloubu I had to do a second investigation on that one and found the first fix wasn't correct
=> fix: do not redeposit dust

contracts/Vault.vy
like python. style is important
=> style: update code style

contracts/Vault.vy
This makes the code easier to understand and safe
=> perf: optimize code

contracts/BaseStrategy.sol, contracts/CommonHealthCheck.sol, tests/functional/strategy/test_common_health_check.py, tests/functional/strategy/test_strategy_health.py
Port 0.3.5 health checks to 0.4.2
=> feat: add health check to 0.4.2

contracts/BaseStrategy.sol, contracts/Vault.vy, contracts/interfaces/ICustomHealthCheck.sol, contracts/test/TestHealthCheck.sol, tests/functional/strategy/test_fees.py, tests/functional/strategy/test_migration.py, tests/functional/strategy/test_shutdown.py, tests/functional/vault/test_losses.py, tests/functional/vault/test_misc.py, tests/functional/vault/test_strategies.py, tests/functional/vault/test_withdrawal.py
Adds the health checks to the vaults.
=> feat: add health check to vault

contracts/BaseStrategy.sol, contracts/BaseWrapper.sol, contracts/test/TestStrategy.sol
See: https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2484
closes #359
=> refactor: use fully qualified library syntax

contracts/Vault.vy
=> feat: more efficient data structure for checking Withdrawal Queue 

contracts/Vault.vy
=> docs: document maxLoss param

contracts/Vault.vy, tests/functional/vault/test_strategies.py
=> fix: issue #414

contracts/BaseWrapper.sol, package.json, yarn.lock
=> chore: update js deps

contracts/BaseStrategy.sol, contracts/BaseWrapper.sol, contracts/test/TestStrategy.sol
This reverts commit e02ad5bb064c4142324775cd81d3929a385e9485.
=> Revert "refactor: use fully qualified library syntax (#401)"

.github/workflows/lint.yaml, .github/workflows/release-drafter.yml, .github/workflows/test.yaml, CONTRIBUTING.md, SECURITY.md, contracts/BaseStrategy.sol, contracts/Vault.vy
we are updating the `master` branch to `main`
=> chore: update yaml

contracts/BaseRouter.sol, contracts/BaseWrapper.sol
Transform the BaseWrapper so that it can handle multiple tokens.
Funds are not held by the router, it acts as a router.
BaseWrapper is rebuilt on top of BaseRouter.
=> feat: base router

contracts/BaseWrapper.sol
=> fix: NatSpec typo in `BaseWrapper.sol`

contracts/Vault.vy, tests/functional/vault/test_strategies.py
Added unit tests to check intended behaviour
=> feat: allow revoke permission from vault manager

contracts/Vault.vy, tests/functional/vault/test_misc.py
=> feat: add deposit and withdraw events

contracts/Vault.vy, tests/functional/vault/test_config.py
=> feat: add event to setLockedProfitDegradation

contracts/CommonHealthCheck.sol, tests/functional/strategy/test_fees.py
Add events to CommonHealthCheck -> setDisabledCheck
https://github.com/yearn/yearn-vaults/issues/503
=> feat: add event to disable health check

contracts/Vault.vy, tests/functional/vault/test_misc.py
=> feat: add event to sweep

README.md
Added instructions on resolving import statements in vscode
=> docs: added import remapping instructions

contracts/BaseStrategy.sol
=> fix: implement modifiers

.github/workflows/lint.yaml, .github/workflows/test.yaml, README.md, requirements-dev.txt, scripts/keep.py, tests/conftest.py, tests/functional/conftest.py, tests/functional/strategy/test_clone.py, tests/functional/strategy/test_migration.py, tests/functional/strategy/test_misc.py, tests/functional/vault/test_config.py, tests/functional/vault/test_losses.py, tests/functional/vault/test_misc.py, tests/functional/vault/test_shares.py, tests/functional/vault/test_strategies.py, tests/functional/vault/test_withdrawal.py, tests/functional/wrappers/test_affliate.py, tests/functional/wrappers/test_ytoken.py, tests/integration/conftest.py, tests/integration/test_operation.py, tests/integration/test_wrapper.py
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> chore: bump ganache version

contracts/Vault.vy
=> fix: gov event

tests/functional/vault/test_misc.py
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> fix: two imports
